# Generated by Django 5.2.10 on 2026-02-15 05:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mqtt_app', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='TankConfig',
        ),
        migrations.DeleteModel(
            name='WaterReading',
        ),
    ]
