# Generated by Django 5.2.10 on 2026-02-15 05:41

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('mqtt_app', '0002_delete_tankconfig_delete_waterreading'),
    ]

    operations = [
        migrations.CreateModel(
            name='WaterReading',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total_height', models.FloatField()),
                ('total_volume', models.FloatField()),
                ('distance', models.FloatField()),
                ('percentage', models.FloatField()),
                ('filled_water_in_volume', models.FloatField()),
                ('battery_voltage', models.FloatField()),
                ('motor_mode', models.IntegerField()),
                ('motor_status', models.IntegerField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
