# Generated by Django 5.2.11 on 2026-06-21 06:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mqtt_app', '0003_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Device',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mac_address', models.CharField(max_length=50, unique=True)),
                ('serial_number', models.CharField(blank=True, max_length=50, null=True)),
                ('device_name', models.CharField(default='Water Tank', max_length=100)),
                ('total_height', models.FloatField(default=3.0)),
                ('total_volume', models.FloatField(default=1000.0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.AddField(
            model_name='waterreading',
            name='device',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='readings', to='mqtt_app.device'),
        ),
    ]
