# Generated by Django 5.2.11 on 2026-07-04 05:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mqtt_app', '0004_device_waterreading_device'),
    ]

    operations = [
        migrations.AddField(
            model_name='device',
            name='max_percentage',
            field=models.FloatField(default=90.0),
        ),
        migrations.AddField(
            model_name='device',
            name='min_percentage',
            field=models.FloatField(default=20.0),
        ),
    ]
