# Generated by Django 5.2.11 on 2026-07-04 06:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mqtt_app', '0005_device_max_percentage_device_min_percentage'),
    ]

    operations = [
        migrations.AddField(
            model_name='device',
            name='deep_sleep',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='device',
            name='sleep_interval',
            field=models.IntegerField(default=300),
        ),
    ]
