# Generated by Django 5.2.11 on 2026-07-04 18:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mqtt_app', '0006_device_deep_sleep_device_sleep_interval'),
    ]

    operations = [
        migrations.AddField(
            model_name='device',
            name='sensor_interval',
            field=models.IntegerField(default=5000),
        ),
    ]
