# Generated by Django 5.2.11 on 2026-07-12 09:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mqtt_app', '0007_device_sensor_interval'),
    ]

    operations = [
        migrations.AddField(
            model_name='waterreading',
            name='faults',
            field=models.IntegerField(default=0),
        ),
    ]
